# Generated by Django 4.0.4 on 2022-07-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_messaging_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
    ]
